baseURL = "https://KeLD0612.github.io/my-network-blog/"
languageCode = "vi"
title = "Blog Lập Trình Mạng | KeLD0612"
theme = "ananke"
relativeURLs = true
canonifyURLs = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Profile"
url = "/profile/"
weight = 3
